// @effect-diagnostics nodeBuiltinImport:off globalConsole:off - This deterministic fixture generator uses synchronous host file APIs.
import * as NodeCrypto from "node:crypto";
import * as NodeFS from "node:fs";
import * as NodeOS from "node:os";
import * as NodePath from "node:path";
import * as NodeSqlite from "node:sqlite";

import { sigidiUpstreamCompatibility } from "@t3tools/shared/sigidiMigrationCompatibility";
import * as Effect from "effect/Effect";

import { migrationManifest, runMigrations } from "../src/persistence/Migrations.ts";
import * as NodeSqliteClient from "../src/persistence/NodeSqliteClient.ts";

const fixtureDirectory = NodePath.resolve(import.meta.dirname, "../src/persistence/fixtures");
const fixturePath = NodePath.join(fixtureDirectory, "upstream-f8707481.sql");
const metadataPath = NodePath.join(fixtureDirectory, "upstream-f8707481.json");
const check = process.argv.includes("--check");

const quote = (value: string) => `'${value.replaceAll("'", "''")}'`;

const expectedManifest = sigidiUpstreamCompatibility.migrations.map(({ id, name }) => [id, name]);
if (JSON.stringify(migrationManifest) !== JSON.stringify(expectedManifest)) {
  throw new Error("The upstream manifest does not match the pinned compatibility record");
}

const tempDirectory = NodeFS.mkdtempSync(
  NodePath.join(NodeOS.tmpdir(), "sigidi-upstream-fixture-"),
);
const databasePath = NodePath.join(tempDirectory, "state.sqlite");

try {
  await Effect.runPromise(
    runMigrations().pipe(Effect.provide(NodeSqliteClient.layer({ filename: databasePath }))),
  );

  const database = new NodeSqlite.DatabaseSync(databasePath);
  const schema = database
    .prepare(
      `
        SELECT sql
        FROM sqlite_schema
        WHERE sql IS NOT NULL
          AND name NOT LIKE 'sqlite_%'
        ORDER BY
          CASE type
            WHEN 'table' THEN 1
            WHEN 'index' THEN 2
            WHEN 'trigger' THEN 3
            WHEN 'view' THEN 4
            ELSE 5
          END,
          name
      `,
    )
    .all() as Array<{ readonly sql: string }>;
  database.close();

  const lines = [
    "-- Generated by apps/server/scripts/generateSigidiUpstreamFixture.ts.",
    `-- Upstream: ${sigidiUpstreamCompatibility.testedUpstreamCommit}`,
    "BEGIN TRANSACTION;",
    ...schema.map(({ sql }) => `${sql};`),
    ...migrationManifest.map(
      ([id, name]) =>
        `INSERT INTO effect_sql_migrations (migration_id, name, created_at) VALUES (${id}, ${quote(name)}, '1970-01-01T00:00:00.000Z');`,
    ),
    "INSERT INTO orchestration_events (sequence, event_id, aggregate_kind, stream_id, stream_version, event_type, occurred_at, command_id, causation_event_id, correlation_id, actor_kind, payload_json, metadata_json) VALUES (1, 'fixture-event', 'project', 'fixture-project', 1, 'fixture.created', '2026-08-03T00:00:00.000Z', NULL, NULL, NULL, 'system', '{}', '{}');",
    "COMMIT;",
    "",
  ];
  const fixture = lines.join("\n");
  const upstreamManifest = migrationManifest
    .map(([id, name]) => `    [${id}, ${JSON.stringify(name)}]`)
    .join(",\n");
  const metadata = `{
  "sourceRevision": ${JSON.stringify(sigidiUpstreamCompatibility.testedUpstreamCommit)},
  "upstreamManifest": [
${upstreamManifest}
  ],
  "sigidiManifest": [],
  "effectEngine": {
    "version": ${JSON.stringify(sigidiUpstreamCompatibility.effectEngine.version)},
    "patchHash": ${JSON.stringify(sigidiUpstreamCompatibility.effectEngine.patchHash)}
  },
  "fixtureSha256": ${JSON.stringify(NodeCrypto.createHash("sha256").update(fixture).digest("hex"))},
  "representativeDataCases": ["orchestration event survives SIGIDI migration startup"]
}\n`;

  if (check) {
    if (
      NodeFS.readFileSync(fixturePath, "utf8") !== fixture ||
      NodeFS.readFileSync(metadataPath, "utf8") !== metadata
    ) {
      throw new Error("The pinned upstream fixture is stale");
    }
    console.log("SIGIDI upstream fixture is current.");
  } else {
    NodeFS.mkdirSync(fixtureDirectory, { recursive: true });
    NodeFS.writeFileSync(fixturePath, fixture);
    NodeFS.writeFileSync(metadataPath, metadata);
    console.log(`Wrote ${NodePath.relative(process.cwd(), fixturePath)}`);
    console.log(`Wrote ${NodePath.relative(process.cwd(), metadataPath)}`);
  }
} finally {
  NodeFS.rmSync(tempDirectory, { recursive: true, force: true });
}
